#!/usr/bin/env python
import sys

variables = sys.stdin.read()
if not variables: # Everything up to date
    sys.exit(0)
local_ref, local_sha, remote_ref, remote_sha = variables.split()

if remote_ref.split("/")[-1] == "master":
    do_checks()
else:
    print "Not submitting to master branch, have fun!"
